import java.math.BigInteger;
import java.util.HashSet;

/**
 * Created by Max Muth on 19.08.14.
 * kontakt@maxi-muth.de
 * <p/>
 * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */
public class Problem029 {

    private static final int MAX = 100;

    public static void main(String[] args) {

        HashSet<BigInteger> cache = new HashSet<BigInteger>();

        for (int a = 2; a <= MAX; a++) {
            for (int b = 2; b <= MAX; b++) {

                cache.add(new BigInteger(String.valueOf(a)).pow(b));

            }
        }

        System.out.println(cache.size());

    }

}
